### ISSUE TITLE
typo in add-https-conn

### ISSUE THREAD

**Issue by petrkalina** [dcm4che-dockerfiles/slapd-dcm4chee#1]
https://github.com/dcm4che-dockerfiles/slapd-dcm4chee/blob/bb7f29f1946b6f22b0382b539ec811a3e53da0b4/ldap/data/add-https-conn.ldif#L87

.. additional q in start of line 87..

**Comment by gunterze** [comment]
Pushed patched `dcm4che/slapd-dcm4chee:2.4.50-23.0`
