### ISSUE TITLE
HL7 port environment variable has an extra 1 at the beginning - Version 5.23.0

### ISSUE THREAD

**Issue by jorgeferhn** [dcm4che-dockerfiles/slapd-dcm4chee#2]
During the creation of the container if you put a custom port (even with 12575), Wildfly adds an extra '1' at the beginnig (must be initialized and the environment variable I assume is being concatenated) causing a port out of range exception.

Attached screenshot of docker-compose.env and Docker container logs

Here is the problem
![2021-01-26 (10)](https://user-images.githubusercontent.com/66940054/105942955-df385700-6025-11eb-803d-9081764bf6ab.png)

Here it is fixed by eliminating the '1' from the docker-compose.env file.
![2021-01-26 (11)](https://user-images.githubusercontent.com/66940054/105942947-de072a00-6025-11eb-98c7-7e586d1c94ae.png)

**Comment by gunterze** [comment]
Caused by https://github.com/dcm4che-dockerfiles/slapd-dcm4chee/commit/e652776d9aff15b896f0c47c37b601c2ee36ea8a for https://github.com/dcm4che/dcm4chee-arc-light/issues/2944

Pushed patched dcm4che/slapd-dcm4chee:2.4.50-23.0
